config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'users#new'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get '/auth/facebook/callback', to: 'sessions#create_facebook'
  post 'login', to: 'sessions#create', as: 'sessions'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  post 'repetitions', to: 'repetitions#create', as: 'repetitions'
  delete 'repetition', to: 'repetitions#destroy', as: 'repetition'
  post 'exercise', to: 'exercise#create', as: 'exercise'


  resources :users, only: [:new, :create, :edit, :update] do
    resources :workouts, only: [:new, :create]
  end

  resources :exercises

  resources :workouts do
    resources :exercises do
      resources :repetitions
    end
  end
 
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :user
  has_many :repetitions
  has_many :exercises, through: :repetitions
  validates :title, presence: true
  validates :title, uniqueness: true
  validates :minutes, presence: true
  validates :minutes, numericality: { integer: true }
  validates :difficulty, presence: true
 

  def self.filter(user_id)
    if !user_id.blank?
      Workout.where(id: user_id)   
    else
      Workout.all
    end
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_user
  before_action :set_workout
  skip_before_action :set_workout, only: [:index, :new, :create]
  before_action :check_login
  helper_method :params

  def new
    @workout = Workout.new
  end

  def index
    @users = User.all
    @workouts = Workout.filter(params[:user])
  end

  def create
    @workout = Workout.find_by(title: workout_params[:title])
    if !@workout.nil?
      if session[:user_id] == @workout.user_id
        redirect_to workout_path(@workout)
      else
        flash[:notice] = "you are not authorized to view this page"
        redirect_to workouts_path
      end
    else
      @workout = Workout.new(workout_params)
      @workout.user_id = session[:user_id]
      @workout.save
      if @workout.save
        @workout = Workout.find_by(title: workout_params[:title])

        redirect_to workout_path(@workout)
      else
        flash[:notice] = []
        @workout.errors.full_messages.each do |msg|
          flash[:notice] << "#{msg}"
        end
        
        redirect_to new_workout_path
      end
    end
  end

  def show
  end

  def edit
  end

  def destroy
    byebug
    @workout.destroy
    
    redirect_to workouts_path
end

  def update
    @workout.update(title: params[:workout][:title], difficulty: params[:workout][:difficulty], minutes: params[:workout][:minutes], workout_type: params[:workout][:workout_type])
    redirect_to workout_path(@workout)
  end

  private
  def set_user
    @user = current_user
  end

  def set_workout
    @workout = Workout.find(params[:id])
  end

  def workout_params
    params.require(:workout).permit(:title, :difficulty, :minutes, :workout_type)
  end

  def check_login
    if !logged_in?
      redirect_to login_path
    end 
  end

end

app/views/workouts/_form.html.erb
<%= f.text_field :title, class: 'fadeIn first', placeholder: 'title' %>

<%= f.text_field :difficulty, class: 'fadeIn second', placeholder: 'difficulty' %>

<%= f.text_field :minutes, class: 'fadeIn third', placeholder: 'minutes' %>

<%= f.text_field :workout_type, class: 'fadeIn fourth', placeholder: 'workout type' %>

<%= f.submit "submit" %>

app/views/workouts/edit.html.erb
<div class="wrapper fadeInDown">
  <div id="formContent">
    <%= form_with model: @workout do |f| %>
       <%= render :partial => 'form', :locals => { :f => f } %>
      <br>
      <%= link_to "delete", workout_path(@workout), controller: :workouts, method: :delete, data: {confirm: 'are you sure?'} %><br>
      <%=link_to "cancel", workout_path(@workout) %>
    <% end %>
</div>

<% if @workout.repetitions.length > 0 %>
  <% @workout.repetitions.each do |rep| %>
    <% @exercise = Exercise.find_by(id: rep.exercise_id) %>
    <div class="card-workout-info">
        <p class="card-content">Name: <%= @exercise.name %></p>
        <p class="card-content">Type: <%= @exercise.exercise_type %></p> 
        <p class="card-content">Equipment: <%= @exercise.equipment %></p>
        <p class="card-content">Reps: <%= rep.reps %></p>
        <p class="card-content">Sets: <%= rep.sets %></p>
        <p class="card=content"><%= @exercise.description %></p>
        <%= link_to 'edit', edit_workout_exercise_repetition_path(rep.workout_id, rep.exercise_id, rep.id) %><br>
        <%= link_to 'remove', workout_exercise_repetition_path(rep.workout_id, rep.exercise_id, rep.id), controller: :repetitions, method: :delete, data: {confirm: 'are you sure?'} %>
    </div>
  <% end %> 
<% end %>

app/views/workouts/home.html.erb
<h1>HOME</h1>

app/views/workouts/index.html.erb
<div class="card-workout-info">
  <h3 class="card-title">Workouts</h3>
  <%= link_to "new workout", new_workout_path %><br>
</div>


<div class="dropdown">
      <%= form_tag("/workouts", method: "get") do %>
      <%= select_tag "user", options_from_collection_for_select(@users, "id", "first_name"), include_blank: 'user name' %>
      <%= submit_tag "Filter" %>
    <% end %>
</div>

<%if !@workouts.nil? %>
  <%@workouts.each do |workout|%>
      <div class="card-workout-info">
        <h5 class="card-title"><%= link_to "#{workout.title}", workout_path(workout) %></h5>
        <p class="card-content">workout type: <%= workout.workout_type %></p>
        <p class="card-content">difficulty: <%= workout.difficulty %></p>
        <p class="card-content"><%= workout.minutes %> minutes</p>
        <p class="card-content">created by <%= workout.user.first_name %></p>
      </div>
  <%end%>
<%end%>

app/views/workouts/new.html.erb
<div class="wrapper fadeInDown">
  <div id="formContent">
    <%= form_with model: @workout do |f| %>
       <%= render :partial => 'form', :locals => { :f => f } %>
      <br>
      <%=link_to "cancel", workouts_path %>
    <% end %>
</div>

app/views/workouts/show.html.erb
<div class="card-workout-info">
    <h3 class="card-title"><%= @workout.title %></h3>
    <h5 class="card-content">workout type: <%= @workout.workout_type %></h5>
    <h5 class="card-content">difficulty: <%= @workout.difficulty %></h5>
    <h5 class="card-content"><%= @workout.minutes %> minutes</h5>
    <p class="card-content">created by <%= @workout.user.first_name %></p>

    <% if current_user.id == @workout.user_id %>
        <%= link_to "edit workout", edit_workout_path(@workout) %><br>
        <%= link_to "add exercises", workout_exercises_path(@workout) %><br>
    <% end %>
    <%= link_to "all workouts", workouts_path %>  
</div>

<% if @workout.repetitions.length > 0 %>
  <% @workout.repetitions.each do |rep| %>
    <% @exercise = Exercise.find_by(id: rep.exercise_id) %>
    <div class="card-workout-info">
        <p class="card-content">Name: <%= @exercise.name %></p>
        <p class="card-content">Type: <%= @exercise.exercise_type %></p> 
        <p class="card-content">Equipment: <%= @exercise.equipment %></p>
        <p class="card-content">Reps: <%= rep.reps %></p>
        <p class="card-content">Sets: <%= rep.sets %></p>
        <p class="card=content"><%= @exercise.description %></p>
        <% if !@workout.nil? %>
          <%= link_to "Add", new_workout_exercise_repetition_path(@workout, @exercise) %></p>
        <% end %>
    </div>
  <% end %> 
<% end %>
  