config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'users#new'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get '/auth/facebook/callback', to: 'sessions#create_facebook'
  post 'login', to: 'sessions#create', as: 'sessions'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  post 'repetitions', to: 'repetitions#create', as: 'repetitions'
  delete 'repetition', to: 'repetitions#destroy', as: 'repetition'
  post 'exercise', to: 'exercise#create', as: 'exercise'


  resources :users, only: [:new, :create, :edit, :update] do
    resources :workouts, only: [:new, :create]
  end

  resources :exercises

  resources :workouts do
    resources :exercises do
      resources :repetitions
    end
  end
 
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :check_login
  
  def new
    @exercise = Exercise.new
  end
  
  def index
    @workout = Workout.find_by(id: params[:workout_id])
    @exercises = Exercise.all
  end
  
  def create
    @exercise = Exercise.find_by(name: params[:exercise][:name])
    if params[:workout]
      @workout = Workout.find(params[:difficulty])
    end
    if !@exercise.nil?
        redirect_to exercises_path
    else
      @exercise = Exercise.create(exercise_params)
      if @exercise.save
        @exercise = Exercise.find_by(name: exercise_params[:name])

        redirect_to exercises_path
      else
        flash[:notice] = []
        @exercise.errors.full_messages.each do |msg|
          flash[:notice] << "#{msg}"
        end
        if !@workout
          redirect_to new_exercise_path
        else
          redirect_to new_workout_exercise_path(@workout)
        end
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_user
    @user = current_user
  end

  def set_exercise
    @exercise = Eercise.find(params[:id])
  end

  def exercise_params
    params.require(:exercise).permit(:name, :exercise_type, :equipment, :description)
  end

  def check_login
    if !logged_in?
      redirect_to login_path
    end 
  end

end

app/views/exercises/_form.html.erb
<% if params[:workout_id] %>
    <%= f.hidden_field :workout_id, :value => params[:workout_id] %>
<% end %>

<%= f.text_field :name, class: 'fadeIn first', placeholder: 'exercise name' %>

<%= f.text_field :exercise_type, class: 'fadeIn second', placeholder: 'exercise type' %>

<%= f.text_field :equipment, class: 'fadeIn third', placeholder: 'equipment' %>

<%= f.text_field :description, class: 'fadeIn fourth', placeholder: 'description' %>

<%= f.submit "submit" %>

app/views/exercises/index.html.erb
<div class="card-workout-info">
  <h3 class="card-title">Exercises</h3>
  <% if !@workout.nil? %>
        <%= link_to "new exercise", new_workout_exercise_path(@workout) %><br>
        <%= link_to "cancel", workout_path(@workout) %>
      <% else %>
        <%= link_to "new exercise", new_exercise_path %><br>
      <% end %>
</div>

<% if @exercises.length > 0 %>
  <% @exercises.each do |exercise| %>
    <div class="card-workout-info">
        <p class="card-content">Name: <%= exercise.name %></p>
        <p class="card-content">Type: <%= exercise.exercise_type %></p> 
        <p class="card-content">Equipment: <%= exercise.equipment %></p>
        <p class="card=content"><%= exercise.description %></p>
        <% if !@workout.nil? %>
          <%= link_to "Add", new_workout_exercise_repetition_path(@workout, exercise) %></p>
        <% end %>
    </div>
  <% end %> 
<% end %>

app/views/exercises/new.html.erb
<div class="wrapper fadeInDown">
    <div id="formContent">
    <% if params[:workout_id] %>
        <% @workout = Workout.find(params[:workout_id])%>
        <%= form_with(model: @exercise, url: workout_exercises_path(@workout), method: :post)  do |f| %>
            <%= render :partial => 'form', :locals => { :f => f } %><br>
        <% end %>
    <% else %>
        <%= form_with model: @exercise  do |f| %>
            <%= render :partial => 'form', :locals => { :f => f } %><br>
        <% end %>
    <% end %>

    <% if params[:workout_id] %>
        <%=link_to "cancel", workout_exercises_path %>
    <% else %>
        <%=link_to "cancel", exercises_path %>
    <% end %>
  </div>
</div>