config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'users#new'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get '/auth/facebook/callback', to: 'sessions#create_facebook'
  post 'login', to: 'sessions#create', as: 'sessions'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  post 'repetitions', to: 'repetitions#create', as: 'repetitions'
  delete 'repetition', to: 'repetitions#destroy', as: 'repetition'
  post 'exercise', to: 'exercise#create', as: 'exercise'


  resources :users, only: [:new, :create, :edit, :update] do
    resources :workouts, only: [:new, :create]
  end

  resources :exercises

  resources :workouts do
    resources :exercises do
      resources :repetitions
    end
  end
 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!--bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!--Google Web Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&family=Roboto:wght@300&display=swap" rel="stylesheet">
    <title>Work It Out</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <!--#navbar-->
  <header class="navbar navbar-expand navbar-dark flex-column flex-md-row bd-navbar">
    <%if logged_in? %>
      <%= link_to 'Work It Out', workouts_path, class: 'navbar-brand' %>
      <div class="navbar-nav-scroll">
        <ul class="navbar-nav bd-navbar-nav flex-row">
          <% @user = current_user  %>
          <li><%= link_to 'new workout', new_user_workout_path(@user), class: 'nav-link' %></li>
          <li><%= link_to 'workouts', workouts_path, class: 'nav-link' %></li>
          <li><%= link_to 'new exercise', new_exercise_path, class: 'nav-link' %></li>
          <li><%= link_to 'exercises', exercises_path, class: 'nav-link' %></li>
          <li><%= link_to 'account', edit_user_path(current_user), class: 'nav-link' %></li>
          <li><%= link_to "logout, #{@user.first_name}", logout_path, class: 'nav-link', method: 'delete' %></li>
        </ul>
      </div>
    <% else %>
      <%= link_to 'Work It Out', sessions_path, class: 'navbar-brand' %>
    <% end %>
  </header>

  <!--#View container-->

  <%= yield %>

  <div class='notice'>
    <% if flash[:notice] %> 
      <% if flash[:notice].is_a?(Array) %>
        <% flash.each do |k, v|%>
          <% v.each do |msg|%>
            <%= content_tag :div, msg %>
          <% end %>  
        <% end %>
      <% else %>
          <%= flash[:notice] %>
      <% end %>
    <% end %>
  </div>
  
  </body>
</html>